### ISSUE TITLE
Update all datasets so the validity checker does not return errors

### ISSUE THREAD

**Issue by biltzerpos** [LePa-YU/Datasets#5]
At the moment, it seems all the errors are because the requires relation is empty in the datasets, and that does not match the info in the isRequiredBy relation. See if removing any empty relations fixes the errors.

**Comment by biltzerpos** [comment]
The inverse relation can be missing completely (then it is assumed to be the exact inverse of what is in the original relation), but if it is explicitly listed in the dataset it has to have the inverse information, otherwise you are asking for bugs to happen.

**Comment by annisiren** [comment]
Ok, that's not how I originally understood it when we talked about the validity checker. You said that only one of them needed to be filled? Is this now not the case?

**Comment by biltzerpos** [comment]
As discussed online, the inverse is either completely missing or exactly matching to the original relation.

**Comment by annisiren** [comment]
Done for now. Will update when new functionalities come for the validity checker.

**Comment by biltzerpos** [comment]
I still see errors for most datasets, so I'm leaving this open.

**Comment by annisiren** [comment]
Did you try it on the dev branch in the validity checker? Otherwise you'll need to specify what errors/warnings are happening because I don't see any.

**Comment by biltzerpos** [comment]
Yes, 4462 has an error about missing columns, FAKE also has 2 errors about the start and end nodes.
All datasets have warnings about particular IDs that should be fixable.

**Comment by annisiren** [comment]
Ok, I'll look into it this afternoon!

**Comment by annisiren** [comment]
Looks like I committed but forgot to push yesterday, whoops. Pushed now :)
